# Generated by Django 4.2.7 on 2023-11-23 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('annotation', models.TextField()),
                ('number_of_credits', models.IntegerField()),
                ('year_of_study', models.IntegerField()),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guaranteed_courses', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='courses_as_student', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(related_name='courses_as_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('repetition', models.CharField(choices=[('Every Week', 'Every Week'), ('Even Week', 'Even Week'), ('Odd Week', 'Odd Week'), ('One-Time Activity', 'One-Time Activity')], max_length=20)),
                ('optional_requirements', models.TextField(blank=True)),
                ('students', models.ManyToManyField(related_name='educational_activities_as_student', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_schedule.course')),
                ('teachers', models.ManyToManyField(related_name='educational_activities_as_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=100, unique=True)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=50)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('educational_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_schedule.educationalactivity')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_schedule.room')),
            ],
        ),
    ]
