# Generated by Django 4.2.7 on 2023-12-16 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uni_schedule', '0003_alter_course_students_alter_course_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalactivity',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='educational_activities_as_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
